### PR TITLE
Removed method annotation without argument from PHPDoc

### PR DESCRIPTION
**Pull request by VoronoyAlexandr**
### Description
Added argument to PHPDoc annotation @method setRowClickCallback(string $value)

### Fixed Issues
[#125 Clean Up Magento/ImportExport/Block/Adminhtml/Export/Filter](https://github.com/magento-engcom/import-export-improvements/issues/125)

### Manual testing scenarios (*)
Run ./vendor/bin/phpstan analyse -l 0 app/code/Magento/ImportExport/Block/Adminhtml/Export/Filter.php

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/import-export-improvements?pullRequest=152) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
@VoronoyAlexandr thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by dmanners** [comment]
Hi @VoronoyAlexandr thanks for this pull request.

Could you check the static tests.

```
Magento\Test\Php\LiveCodeTest::testCodeStyle
PHP Code Sniffer detected 2 violation(s): 

FILE: /var/www/html/app/code/Magento/Backend/Block/Widget/Grid.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 152 | ERROR | [x] Missing short description
 153 | ERROR | [x] There must be exactly one blank line before tags
 712 | ERROR | [x] There must be exactly one blank line between lines
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

Thanks

**Comment by VoronoyAlexandr** [comment]
Good day @dmanners . Done with this errors.

**Review by dmanners — APPROVED** [review]
Looks good, let me process this PR for you.

**Pull request merged**
